### ISSUE TITLE
change里面打印出了value，显示NaN 就划不动咯

### ISSUE THREAD

**Issue by baishuiraodongcheng** [AlloyTeam/PhyTouch#133]
change里面打印出了value，显示NaN 就划不动咯

**Comment by a542006055** [comment]
n这个问题你有解决吗

**Comment by dntzhang** [comment]
试试v0.1.1

**Comment by a542006055** [comment]
谢谢&nbsp; 我试试 因为这个bug=极其难复现，可能五十次会有一次那种概率




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "当耐特"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 下午3:22
收件人: "AlloyTeam/PhyTouch"<PhyTouch@noreply.github.com&gt;; 
抄送: "542006055"<542006055@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [AlloyTeam/PhyTouch] change里面打印出了value，显示NaN 就划不动咯 (#133)





 
Closed #133.
