### ISSUE TITLE
change的参数会出现NAN？？

### ISSUE THREAD

**Issue by gongsan9527** [AlloyTeam/PhyTouch#134]
change的参数会出现NAN？？
![a8811876763b6f97e00be2763dfde16](https://user-images.githubusercontent.com/4644769/72219767-78640f00-3584-11ea-9f62-16871a9e4a9d.jpg)

**Comment by dntzhang** [comment]
用的 alloytouch 哪个版本， phy-touch 修复了

**Comment by gongsan9527** [comment]
> 用的 alloytouch 哪个版本， phy-touch 修复了

就是最新的phy-touch

**Comment by weitingGao** [comment]
我也是，经常性出现NaN

**Comment by bemzj** [comment]
我用了最新版本还是会，极小概率出现NaN

**Comment by xuanye** [comment]
最新版问题依然出现，也不算小概率吧。。。挺多见的。。

**Comment by bemzj** [comment]
> > 用的 alloytouch 哪个版本， phy-touch 修复了
> 
> 就是最新的phy-touch。@dntzhang
> ![QQ图片20200113145644](https://user-images.githubusercontent.com/4644769/72237338-0be52080-3615-11ea-9304-ac8174733902.png)

我用了新版的还会，在手机上还会

**Comment by rhapp** [comment]
change的参数又多次出现了NAN? 我也用的是新版的phy-touch

**Comment by dntzhang** [comment]
安装 v0.1.1
