### ISSUE TITLE
GH page does not work anymore

### ISSUE THREAD

**Issue by DanielRuf** [AlloyTeam/PhyTouch#135]
http://alloyteam.github.io/AlloyTouch/

Also it would be great to translate more to English, I can hardly read and understand the code.

**Comment by dntzhang** [comment]
fixed

**Comment by DanielRuf** [comment]
Still 404. What is the new URL?

**Comment by DanielRuf** [comment]
Ah, it is http://alloyteam.github.io/PhyTouch/ now =)

You could have mentioned it ;-)

**Comment by dntzhang** [comment]
Many thanks!
