### ISSUE TITLE
 spring: false这个效果触发不了

### ISSUE THREAD

**Issue by cailven** [AlloyTeam/PhyTouch#14]
Demo里关闭回弹效果的spring: false貌似是假的吧，review了源码，发现根本没有spring属性。那现在想要关闭回弹让它到了max，min直接划不过去怎么做？

**Comment by kmdjs** [comment]
@cailven 
禁止回弹的功能已经去掉了。我更新下readme~~
有刚需？

**Comment by cailven** [comment]
是的，我现在有两个问题：
1、我现在要用禁止回弹，能跟我讲一下怎么做么？
——————————————————————————————
2、还有一个bug就是打开inertia后，惯性不正常，拖动会往相反的方向运行惯性。
我的参数如下：
            touch: this.renderer.domElement,
            vertical: false,
            bindSelf: true,
            target: this.dae.rotation,
            property: "y",
            spring: false, //不必需,是否有回弹效果。默认是true
            sensitivity: 1,//不必需,触摸区域的灵敏度，默认值为1，可以为负数
            factor: 0.005,               //运动期间的摩擦力
            moveFactor: 0.05,       //拖拽期间的摩擦力
            max: -2,
            min: -26.7,
            // preventDefault: false,
           inertia: true,

项目用于threejs，旋转一个外部模型文件，因为今晚要上线，急需帮助，谢谢啦。

**Comment by kmdjs** [comment]
把这个去掉

max: -2,
min: -26.7,

**Comment by cailven** [comment]
去掉后，那我拖动旋转的限制怎么做呢？

**Comment by kmdjs** [comment]
@cailven 
360度旋转会呈现周期性的~~

**Comment by cailven** [comment]
threejs的this.dae.rotation.y没有出现周期性。这个我测过了，是恒定的值。回弹的事情怎么解决呢？能把限制写在onChange里面吗？

**Comment by kmdjs** [comment]
怎么会没有周期性？
你看我发的链接里的代码就是操作rotation.y

```js
 new AlloyTouch({
        touch: renderer.domElement,
        vertical: false,
        bindSelf : true,
        target: mesh.rotation,
        property: "y",
        factor: 0.08,
        moveFactor: 0.01
    })
```

**Comment by cailven** [comment]
可能因为我旋转的角度在一个周期里的原因吧。行我去掉。能跟我讲一下去掉回弹的方法吗？

**Comment by kmdjs** [comment]
把这个去掉

max: -2,
min: -26.7,

这样就没有回弹。

**Comment by cailven** [comment]
那旋转的限制呢？怎么做？或者之后不是旋转的问题怎么限制回弹？回弹的事情既然之前想过spring总归需要个解决方案比较好吧，不需要回弹的场景其实很多的。

**Comment by kmdjs** [comment]
ok~~  我们考虑把spring功能加回去。多谢建议。

**Comment by cailven** [comment]
我自己先用了个hack方法貌似目前是可以的
   change: function () {
               val= Math.max(Math.min(val, MaxVal), MinVal);
}
不用官方的max,min.在即在change里限制。也可以取消回弹了。

**Comment by kmdjs** [comment]
:+1:
