### ISSUE TITLE
factor，moveFactor值太小，惯性不正常。

### ISSUE THREAD

**Issue by cailven** [AlloyTeam/PhyTouch#15]
threejs旋转问题中：

factor: 0.005, 
moveFactor: 0.05,
以上这样惯性不正常（会往反方向运动），然而根据，http://alloyteam.github.io/AlloyTouch/example/threejs/的demo里的参数
  
 factor: 0.08,              
 moveFactor: 0.01,
惯性就正常了，

接下来问题来了，想要增大阻力让运动变小，就没辙了。请问这算bug伐？

**Comment by kmdjs** [comment]
把factor调小
