### ISSUE TITLE
AlloyTouch的关于threejs的官方demo有bug!

### ISSUE THREAD

**Issue by cailven** [AlloyTeam/PhyTouch#16]
访问如下：http://alloyteam.github.io/AlloyTouch/example/threejs

bug描述：拖拽后在惯性的时候没有停下来，就执行第二次拖拽，盒子不见了！
复现率：100%；

**Comment by kmdjs** [comment]
什么手机和系统以及浏览器？我这里并不能复现

**Comment by cailven** [comment]
bug2：
同样这个官方demo，用chrome模拟器测试时候，在拖拽释放惯性时候，鼠标在释放模式从反向移动过去，然后释放变得不正常了，会根据鼠标move的交互而影响，貌似是move的判断没有加在touchstart里面，也没有监听touchend.

**Comment by kmdjs** [comment]
模拟器里丢失touchend是正常现象
